apiVersion: seed.ibm.com/v1
kind: Function
metadata:
  name: en2shakespeare
spec:
  packages:
  - name: lib
    actions:
    - codeUri: https://rawgit.com/kerryspchang/translation-demo/master/lib/en2shakespeare.js
      runtime: nodejs:6
      parameters:
      - name: apiKey
        valueFrom:
          secretKeyRef:
            name: ${projectName}-secret
            key: ftApiKey  

---
apiVersion: seed.ibm.com/v1
kind: CloudService
metadata:
  name: mytranslator
spec:
  service: language_translator
  plan: lite
---
apiVersion: seed.ibm.com/v1
kind: Function
metadata:
  name: watson-language
spec:
  packages:
  - bind:  /whisk.system/watson-translator
    service: mytranslator

---
apiVersion: seed.ibm.com/v1
kind: Function
metadata:
  name: main
spec:
  packages:
  - name: default
    actions:
    - name: translation-demo
      runtime: app
      codeUri: https://rawgit.com/starpit/translation-demo/master/composition.js
